### ISSUE TITLE
error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

### ISSUE THREAD

**Issue by mudasar477** [citrusvanilla/multiplewavetracking_py#1]
Traceback (most recent call last):
  File "D:\Panacea_Logics\multiplewavetracking_py\mwt.py", line 232, in <module>
    main(sys.argv[1:])
  File "D:\Panacea_Logics\multiplewavetracking_py\mwt.py", line 219, in main
    write_output=True)
  File "D:\Panacea_Logics\multiplewavetracking_py\mwt.py", line 122, in analyze
    num_frames)
  File "D:\Panacea_Logics\multiplewavetracking_py\mwt_tracking.py", line 80, in track
    wave.update_points(frame)
  File "D:\Panacea_Logics\multiplewavetracking_py\mwt_objects.py", line 139, in update_points
    res = cv2.bitwise_and(frame, frame, mask=img)
cv2.error: OpenCV(4.0.1) C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

**Comment by gsalgado** [comment]
I got the same error and in my case I've tracked it down to be caused by not having the correct dimensions for the video. As described in the README, the video should be 1280x720. That video will then be downsized by a factor of four in the preprocessing step, and the new size (320x180) has to match the size of the mask passed to cv2.bitwise_and().

Ideally it should be able to deal with videos of any dimensions, but that may require a significant amount of work, so at least it should stop and warn the user before even attempting to process a video with a size other than 1280x720

**Comment by gsalgado** [comment]
As a workaround, you can modify RESIZE_FACTOR in mwt_preprocessing.py so that when it's applied to your video size you get 320x180

**Comment by mudasar477** [comment]
> As a workaround, you can modify RESIZE_FACTOR in mwt_preprocessing.py so that when it's applied to your video size you get 320x180

Thanks you solved my problem.

**Comment by negrolio** [comment]
> As a workaround, you can modify RESIZE_FACTOR in mwt_preprocessing.py so that when it's applied to your video size you get 320x180

and how do you do that?
